apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: analytics-api-17670
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/analytics-api-17670
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
